zuul:
  routes:
    con:
      path: /consumer/**
      serviceId: consumer
    pro:
      path: /producer/**
      serviceId: producer
  ignored-services: pro  #忽略服务，防止服务入侵。不好使
  ignored-patterns: [/**/test1/**] # 忽略接口


#producer:
#  ribbon:
#    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#    listOfServers: localhost:9100,localhost:9101
